<#
.SYNOPSIS
  Categorize the agent skills installed under .claude/skills by domain.

.DESCRIPTION
  Parses each .claude/skills/<name>/SKILL.md frontmatter, assigns a domain
  category, writes a grouped catalog to SKILLS.md, and prints a console summary.

  By default NOTHING is moved (safe). Pass -Move to physically group the skill
  folders into category subfolders -- but note Claude Code discovers skills at
  the FLAT path .claude/skills/<name>/SKILL.md, so nesting can hide them from
  the agent, and re-running `npx autoskills` resets the flat layout.

.EXAMPLE
  .\organizar-skills.ps1
  .\organizar-skills.ps1 -Move
#>
[CmdletBinding()]
param(
  [string]$SkillsDir = (Join-Path $PSScriptRoot '.claude\skills'),
  [string]$Output    = (Join-Path $PSScriptRoot 'SKILLS.md'),
  [switch]$Move
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $SkillsDir)) {
  Write-Error "Skills directory not found: $SkillsDir"
  exit 1
}

# Ordered rules: first pattern (matched against the skill folder name) wins.
$rules = @(
  @{ Cat = '3D / Three.js';              Pattern = '^(threejs|react-three-fiber)' },
  @{ Cat = 'Animation / GSAP';           Pattern = '^gsap' },
  @{ Cat = 'Styling / Tailwind + shadcn';Pattern = '^(shadcn|tailwind)' },
  @{ Cat = 'Design / UI-UX';             Pattern = '(design|taste|brandkit|ui-ux|minimalist-ui|industrial-brutalist|huashu|imagegen|image-to-code|redesign|graphic)' },
  @{ Cat = 'React';                      Pattern = '^(react-best-practices|composition-patterns)$' },
  @{ Cat = 'Web Quality (a11y/SEO/perf)';Pattern = '^(accessibility|seo|core-web-vitals)$' },
  @{ Cat = 'Tooling / Testing';          Pattern = '^(vite|vitest|playwright|full-output-enforcement)' },
  @{ Cat = 'Node.js';                    Pattern = '^nodejs' },
  @{ Cat = 'Deployment';                 Pattern = '^deploy' },
  @{ Cat = 'Video / Remotion';           Pattern = '^remotion' },
  @{ Cat = 'Meta / Skills';              Pattern = '^find-skills$' }
)

function Get-Category([string]$name) {
  foreach ($r in $rules) { if ($name -match $r.Pattern) { return $r.Cat } }
  return 'Other'
}

function Get-Frontmatter([string]$path) {
  $fmName = $null; $fmDesc = $null
  foreach ($line in Get-Content $path) {
    if (-not $fmName -and $line -match '^\s*name:\s*(.+?)\s*$')        { $fmName = $matches[1] }
    elseif (-not $fmDesc -and $line -match '^\s*description:\s*(.+?)\s*$') { $fmDesc = $matches[1] }
    if ($fmName -and $fmDesc) { break }
  }
  [pscustomobject]@{ Name = $fmName; Description = $fmDesc }
}

$skills = foreach ($dir in (Get-ChildItem $SkillsDir -Directory | Sort-Object Name)) {
  $md = Join-Path $dir.FullName 'SKILL.md'
  if (-not (Test-Path $md)) { continue }
  $fm = Get-Frontmatter $md
  $nm = if ($fm.Name) { $fm.Name } else { $dir.Name }
  $short = if ($fm.Description) { $fm.Description } else { '' }
  $dot = $short.IndexOf('. ')
  if ($dot -gt 0) { $short = $short.Substring(0, $dot + 1) }
  if ($short.Length -gt 160) { $short = $short.Substring(0, 157) + '...' }
  [pscustomobject]@{
    Name     = $nm
    Dir      = $dir.Name
    Category = (Get-Category $dir.Name)
    Short    = $short
  }
}

$groups = $skills | Group-Object Category | Sort-Object Name

# --- Write the Markdown catalog (UTF-8, no BOM) ---
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# Skills catalog')
[void]$sb.AppendLine('')
[void]$sb.AppendLine("_$($skills.Count) skills installed via autoskills, grouped by domain. Generated by organizar-skills.ps1 -- do not edit by hand._")
[void]$sb.AppendLine('')
foreach ($g in $groups) {
  [void]$sb.AppendLine("## $($g.Name) ($($g.Count))")
  [void]$sb.AppendLine('')
  foreach ($s in ($g.Group | Sort-Object Name)) {
    [void]$sb.AppendLine("- **$($s.Name)** -- $($s.Short)")
  }
  [void]$sb.AppendLine('')
}
[System.IO.File]::WriteAllText($Output, $sb.ToString())
Write-Host "Wrote catalog: $Output" -ForegroundColor Green

# --- Console summary ---
Write-Host ''
Write-Host 'Skill categories:' -ForegroundColor Cyan
$groups | ForEach-Object { Write-Host ('{0,-34} {1,3}' -f $_.Name, $_.Count) }
Write-Host ('{0,-34} {1,3}' -f 'TOTAL', $skills.Count) -ForegroundColor Cyan

# --- Optional physical grouping (opt-in) ---
if ($Move) {
  Write-Host ''
  Write-Warning 'Moving skills into category subfolders. Claude Code discovers skills at the FLAT path .claude/skills/<name>/SKILL.md; nesting may hide them from the agent, and `npx autoskills` will reset the flat layout.'
  foreach ($s in $skills) {
    $folder = ($s.Category -replace '[\\/:*?"<>|()]', '' -replace '\s+', '-')
    $catDir = Join-Path $SkillsDir $folder
    if (-not (Test-Path $catDir)) { New-Item -ItemType Directory -Path $catDir | Out-Null }
    Move-Item -Path (Join-Path $SkillsDir $s.Dir) -Destination (Join-Path $catDir $s.Dir)
  }
  Write-Host 'Done moving skills into category subfolders.' -ForegroundColor Yellow
}
